# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [4]:
#list(a) 僅是讓最外層轉換為 List ，內層部分仍是 Array。
#tolist() 則是將外層到內層皆轉換為 List 。

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [3]:
# 記得先 Import 正確的套件

import numpy as np

In [4]:

a = np.random.randint(10, size=6) 

print(a)
print(a.ndim)    #此為一維陣列
print(a.shape)   #此陣列的一維的空間大小為 6
print(a.size)    #此陣列含有 6 個元素
print(a.dtype)   #此陣列的資料型態為 int32
print(a.itemsize)#每個元素占用的為 4 bytes
print(a.data)    #資料所儲存的 address 為 0x00000247D5CEEAC0

[0 3 7 7 7 3]
1
(6,)
6
int32
4


In [5]:
b = np.random.randint(10, size=(3,4)) 

print(b)
print(b.ndim)    #此為二維陣列
print(b.shape)   #此陣列的一維的空間大小為 3，
                 # 二維的空間大小為 4。
print(b.size)    #此陣列含有 12 個元素
print(b.dtype)   #此陣列的資料型態為 int32
print(b.itemsize)#每個元素占用的為 4 bytes
print(b.data)    #資料所儲存的 address 為 0x00000247D6AA42B0

[[9 5 2 0]
 [1 7 2 2]
 [3 8 6 2]]
2
(3, 4)
12
int32
4


In [6]:
c = np.random.randint(10, size=(2,3,2)) 

print(c)
print(c.ndim)    #此為三維陣列
print(c.shape)   #此陣列的一維的空間大小為 2
                 # 二維的空間大小為 3
                 # 三維的空間大小為 2
print(c.size)    #此陣列含有 12 個元素
print(c.dtype)   #此陣列的資料型態為 int32
print(c.itemsize)#每個元素占用的為 4 bytes
print(c.data)    #資料所儲存的 address 為 0x00000247D6767220

[[[6 2]
  [3 7]
  [5 7]]

 [[0 7]
  [1 9]
  [2 8]]]
3
(2, 3, 2)
12
int32
4


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [7]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[0, 2, 2, 1, 3, 3]
[0, 2, 2, 1, 3, 3]


In [9]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[2, 3, 8, 9], [0, 0, 8, 7], [9, 1, 3, 9]]
[array([2, 3, 8, 9]), array([0, 0, 8, 7]), array([9, 1, 3, 9])]


In [10]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(cx))


[[[2, 1], [6, 7], [9, 0]], [[1, 7], [9, 0], [7, 2]]]
[array([[2, 1],
       [6, 7],
       [9, 0]]), array([[1, 7],
       [9, 0],
       [7, 2]])]


In [13]:
def tolist(iterable):
    if(iterable.ndim == 1):
        return list(iterable)
    elif(iterable.ndim == 2):
        x = list(iterable)
        for i in range(iterable.shape[0]):
            x[i] = list(iterable[i])
        return list(x)
    elif(iterable.ndim == 3):
        x = list(iterable)
        for i in range(c.shape[0]):
            x[i] = list(iterable[i])
            for j in range(iterable.shape[1]):
                x[i][j] = list(iterable[i][j])
        return list(x)
print(tolist(a))
print(tolist(b))
print(tolist(c))

[0, 2, 2, 1, 3, 3]
[[2, 3, 8, 9], [0, 0, 8, 7], [9, 1, 3, 9]]
[[[2, 1], [6, 7], [9, 0]], [[1, 7], [9, 0], [7, 2]]]
